# Generated by Django 3.2.8 on 2021-10-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_userfriends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='userHash',
            field=models.CharField(editable=False, max_length=64),
        ),
    ]
