# Generated by Django 3.2.8 on 2021-11-02 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_userprofile_randompic'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='isRandom',
            field=models.BooleanField(default=False),
        ),
    ]
