# Generated by Django 3.2.9 on 2021-11-14 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_delete_randomchat'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='isRandom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='randomChatId',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.CreateModel(
            name='RandomFrnd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1consent', models.BooleanField(default=False)),
                ('user2consent', models.BooleanField(default=False)),
                ('user1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='random_frnd', to='accounts.userprofile')),
                ('user2', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='random_self', to='accounts.userprofile')),
            ],
        ),
    ]
