# Generated by Django 3.2.9 on 2021-11-13 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_delete_randomchat'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='isRandom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='randomChatId',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
