# Generated by Django 3.2.9 on 2021-11-15 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20211114_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='randomAlias',
            field=models.CharField(blank=True, default='Anonymous', max_length=30),
        ),
    ]
