# Generated by Django 3.2.8 on 2021-10-27 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('userBio', models.CharField(blank=True, default='Hello World!', max_length=150)),
                ('userPic', models.ImageField(blank=True, null=True, upload_to='userData/profilePic/')),
                ('isOnline', models.BooleanField(default=False)),
                ('randomAlias', models.CharField(blank=True, max_length=20)),
                ('userHash', models.CharField(max_length=64)),
                ('randomPic', models.IntegerField(null=True)),
            ],
        ),
    ]
