# Generated by Django 3.2.9 on 2021-11-08 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_userprofile_randompic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='randomAlias',
            field=models.CharField(blank=True, default='Anonymous', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='randomPic',
            field=models.ImageField(blank=True, default='profilePics/anonymous.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='userPic',
            field=models.ImageField(default='profilePics/default.jpg', null=True, upload_to='profilePics/'),
        ),
    ]
