# Generated by Django 3.2.9 on 2021-11-10 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20211108_1759'),
        ('accounts', '0007_userprofile_israndom'),
    ]

    operations = [
    ]
