# Generated by Django 3.2.9 on 2021-11-11 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_merge_20211109_1838'),
        ('accounts', '0008_merge_20211110_1512'),
    ]

    operations = [
    ]
