# Generated by Django 3.2.9 on 2021-11-11 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0009_merge_20211111_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomChat',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='randomChatData', serialize=False, to='auth.user')),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='isRandom',
        ),
    ]
