# Generated by Django 3.2.9 on 2021-11-12 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20211112_1938'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RandomChat',
        ),
    ]
