# Generated by Django 3.2.9 on 2021-11-13 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0006_randomchat'),
    ]

    operations = [
        migrations.AddField(
            model_name='randomchat',
            name='isPair',
            field=models.BooleanField(default=False),
        ),
    ]
