# Generated by Django 3.2.9 on 2021-11-13 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_randomchat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='randomchat',
            name='RandomChatId',
        ),
        migrations.RemoveField(
            model_name='randomchat',
            name='isPaired',
        ),
    ]
