# Generated by Django 3.2.9 on 2021-11-13 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_auto_20211113_1733'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RandomChat',
        ),
    ]
