# Generated by Django 3.2.9 on 2021-11-13 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('chats', '0005_delete_randomchat'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomChat',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='randomChatData', serialize=False, to='auth.user')),
                ('chatId', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
