randNames = ["shaquille_oatmeal",
             "hanging_with_my_gnomies",
             "hoosier-daddy",
             "fast_and_the_curious",
             "averagestudent",
             "BadKarma",
             "google_was_my_idea",
             "cute_as_ducks",
             "casanova",
             "real_name_hidden",
             "HairyPoppins",
             "fedora_the_explorer",
             "OP_rah",
             "YellowSnowman",
             "Joe Not Exotic",
             "username_copied",
             "whos_ur_buddha",
             "unfinished_sentenc",
             "AllGoodNamesRGone",
             "Something",
             "me_for_president",
             "tinfoilhat",
             "oprahwindfury",
             "anonymouse",
             "Definitely_not_an_athlete",
             "HeartTicker",
             "YESIMFUNNY",
             "BenAfleckIsAnOkActor",
             "magicschoolbusdropout",
             "Everybody",
             "regina_phalange",
             "PawneeGoddess",
             "pluralizes_everythings",
             "chickenriceandbeans",
             "test_name_please_ignore",
             "IYELLALOT",
             "heyyou",
             "laugh_till_u_pee",
             "aDistraction",
             "crazy_cat_lady",
             "banana_hammock",
             "thegodfatherpart4",
             "unfriendme",
             "babydoodles",
             "fluffycookie",
             "buh-buh-bacoenown",
             "ashley_said_what",
             "LactoseTheIntolerant",
             "ManEatsPants",
             "Twentyfourhourpharmacy"
             ]

import random
def randNamefn():
    return randNames[random.randint(0,49)]

